const routes = {
  '/dashboard': 'Home',
  '/components': 'Components',
  '/charts': 'Charts',
  '/components/buttons': 'Buttons',
  '/components/social-buttons': 'Social Buttons',
  '/components/cards': 'Cards',
  '/components/forms': 'Forms',
  '/components/modals': 'Modals',
  '/components/switches': 'Switches',
  '/components/tables': 'Tables',
  '/components/tabs': 'Tabs',
  '/icons': 'Icons',
  '/icons/font-awesome': 'Font Awesome',
  '/icons/simple-line-icons': 'Simple Line Icons',
  '/widgets': 'Widgets',
  '/slider': 'Slider',
  '/slider/all': 'All Slider ',
  '/slider/new': 'New Slider',
  '/slider/edit': 'Edit',
  '/slider/edit/:id': 'Edit Detail',
  '/page': 'Page',
  '/page/all': 'All Page',
  '/page/new': 'New Page',
  '/page/edit': 'Edit Page',
  '/blog': 'Blog',
  '/blog/all': 'All Blog',
  '/blog/new': 'New Blog',
  '/blog/category': 'Blog Category',
  '/blog/category/all': 'All Category',
  '/blog/category/new': 'New Category',
  '/blog/category/edit': 'Edit Category',
  '/plugin': 'Plugin',
  '/plugin/google': 'Google',
  '/plugin/foursquare': 'Foursquare',
  '/plugin/mailchimp': 'Mailchimp',
  '/plugin/cloudinary': 'Cloudinary',
  '/plugin/mailgun': 'Mailgun',
  '/plugin/sendgrid': 'Sendgrid',
  '/plugin/flickr': 'Flickr',
  '/setting': 'Setting',
  '/member': 'Member',
  '/member/all': 'All Member',
  '/member/edit': 'Edit Member',
  '/member/block': 'Blocked Member',
  '/member/suspend': 'Suspend Member',
  '/setting/tempo/all': 'All Tempo',
  '/setting/tempo/new': 'New Tempo',
  '/setting/tempo/edit': 'Edit Tempo',
  '/setting/sector/all': 'All Sector',
  '/setting/sector/new': 'New Sector',
  '/setting/sector/edit': 'Edit Sector',
  '/setting/amount': 'Amount',
  '/withdraw': 'Withdraw',
  '/withdraw/all': 'All Withdraw',
  '/withdraw/unpaid': 'Unpaid Withdraw',
  '/withdraw/paid': 'Paid Withdraw',
  '/withdraw/pay': 'Pay Withdraw',
  '/invoice': 'Invoice',
  '/invoice/all': 'All Invoice',
  '/invoice/edit': 'Edit Invoice',
  '/invoice/new': 'New Invoice',
  '/invoice/accept': 'Accept Invoice',
  '/invoice/cancel': 'Cancel Invoice',
  '/customer': 'Customer',
  '/customer/all': 'All Customer',
  '/customer/edit': 'Edit Customer',
  '/customer/block': 'Block Customer',
  '/customer/suspend': 'Suspend Customer',

};
export default routes;
